# GitHub Sponsors - your GitHub username
github: rodrigobrancaglion

# Ko-fi - your Ko-fi username
ko_fi: rodrigobrancaglion

# Custom links (up to 4 URLs)
custom:
  - https://paypal.me/rodrigobrancaglion
