services:
  app:
    image: ghcr.io/freekode/tp2intervals:latest
    container_name: tp2intervals
    restart: unless-stopped
    volumes:
      - ./tp2intervals.sqlite:/tp2intervals.sqlite
    ports:
      - '8080:8080'
