name: Build branches

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extract_branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch_name }}  # Define the job output

    steps:
      - name: Extract Branch Name
        id: extract_branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Use the Branch Name
        run: |
          echo "The branch name is ${{ steps.extract_branch.outputs.branch_name }}"      

  jar:
    uses: ./.github/workflows/workflow-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar

  docker-image:
    needs:
      - jar
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      image-name: tp2intervals
      image-tag: ${{ github.ref }}
      dry-run: false

  electron:
    needs:
      - jar
    strategy:
      matrix:
        environment:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    uses: ./.github/workflows/workflow-electron.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      os: ${{ matrix.environment.os }}
