name: Build branches

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jar:
    uses: ./.github/workflows/workflow-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar

  docker-image:
    needs:
      - jar
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      image-name: tp2intervals

  electron:
    needs:
      - jar
    strategy:
      matrix:
        environment:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    uses: ./.github/workflows/workflow-electron.yml
    with:
      os: ${{ matrix.environment.os }}
