name: Release

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  jar:
    uses: ./.github/workflows/workflow-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      dry-run: false

  docker-image:
    needs:
      - jar
    uses: ./.github/workflows/workflow-docker-image.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      image-name: tp2intervals
      dry-run: false

  electron:
    needs:
      - jar
    strategy:
      matrix:
        environment:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    uses: ./.github/workflows/workflow-electron.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      os: ${{ matrix.environment.os }}
      dry-run: false
