name: Build Docker

on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string
      jar-artifact-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: true

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: ${{ inputs.jar-artifact-name }}
          path: artifact

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ inputs.image-name }} --build-arg JAR_PATH=artifact/${{ inputs.jar-name }}.jar

      - name: Log into registry
        if: ${{ inputs.dry-run == false }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: ${{ inputs.dry-run == false }}
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${{ inputs.image-name }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          docker tag ${{ inputs.image-name }} $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
