name: Workflow JAR

on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string
      jar-artifact-name:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: true

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Build UI
        run: |
          npm ci --prefix ui
          npm run build --prefix ui

      - name: Copy UI
        run: cp -r ui/dist/ui/browser boot/src/main/resources/static

      - name: Build boot
        env:
          APP_DEFAULT_CONFIG_INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
          APP_DEFAULT_CONFIG_INTERVALS_ATHLETE_ID: ${{ secrets.INTERVALS_ATHLETE_ID }}
          APP_DEFAULT_CONFIG_TRAINING_PEAKS_AUTH_COOKIE: ${{ secrets.TRAINING_PEAKS_AUTH_COOKIE }}
          APP_DEFAULT_CONFIG_TRAINER_ROAD_AUTH_COOKIE: my-fav-cookie
          APP_DEFAULT_CONFIG_TRAINER_ROAD_REMOVE_HTML_TAGS: true
        run: |
          cd ./boot
          ./gradlew build

      - name: Cypress tests
        run: |
          npm ci --prefix cypress
          java -jar boot/build/libs/tp2intervals.jar \
            --app.default-config.intervals.api-key=${{ secrets.INTERVALS_API_KEY }} \
            --app.default-config.intervals.athlete-id=${{ secrets.INTERVALS_ATHLETE_ID }} \
            --app.default-config.training-peaks.auth-cookie=${{ secrets.TRAINING_PEAKS_AUTH_COOKIE }} \
          & npm test --prefix cypress

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.jar-artifact-name }}
          path: boot/build/libs/${{ inputs.jar-name }}.jar
          if-no-files-found: error
          compression-level: 0

      - uses: ncipollo/release-action@v1
        if: ${{ inputs.dry-run == false }}
        with:
          draft: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          artifacts: boot/build/libs/${{ inputs.jar-name }}.jar
